export class VehicleRegistration {
  dateOfLastUpdate: Date | null;
  colour: string | null;
  vehicleClass: string | null;
  certificateOfDestructionIssued: boolean | null;
  engineNumber: string | null;
  engineCapacity: string | null;
  transmissionCode: string | null;
  exported: boolean | null;
  yearOfManufacture: string | null;
  wheelPlan: string | null;
  dateExported: object | null;
  scrapped: boolean | null;
  transmission: string | null;
  dateFirstRegisteredUk: Date | null;
  model: string | null;
  gearCount: number | null;
  importNonEu: boolean | null;
  previousVrmGb: object | null;
  grossWeight: number | null;
  doorPlanLiteral: string | null;
  mvrisModelCode: object | null;
  vin: string | null;
  vrm: string | null;
  dateFirstRegistered: Date | null;
  dateScrapped: object | null;
  doorPlan: string | null;
  yearMonthFirstRegistered: string | null;
  vinLast5: string | null;
  vehicleUsedBeforeFirstRegistration: boolean | null;
  maxPermissibleMass: number | null;
  make: string | null;
  makeModel: string | null;
  transmissionType: string | null;
  seatingCapacity: number | null;
  fuelType: string | null;
  co2Emissions: number | null;
  imported: boolean | null;
  mvrisMakeCode: object | null;
  previousVrmNi: object | null;
  vinConfirmationFlag: object | null;

  constructor(data: any) {
    this.dateOfLastUpdate = data.DateOfLastUpdate;
    this.colour = data.Colour;
    this.vehicleClass = data.VehicleClass;
    this.certificateOfDestructionIssued = data.CertificateOfDestructionIssued;
    this.engineNumber = data.EngineNumber;
    this.engineCapacity = data.EngineCapacity;
    this.transmissionCode = data.TransmissionCode;
    this.exported = data.Exported;
    this.yearOfManufacture = data.YearOfManufacture;
    this.wheelPlan = data.WheelPlan;
    this.dateExported = data.DateExported;
    this.scrapped = data.Scrapped;
    this.transmission = data.Transmission;
    this.dateFirstRegisteredUk = data.DateFirstRegisteredUk;
    this.model = data.Model;
    this.gearCount = data.GearCount;
    this.importNonEu = data.ImportNonEu;
    this.previousVrmGb = data.PreviousVrmGb;
    this.grossWeight = data.GrossWeight;
    this.doorPlanLiteral = data.DoorPlanLiteral;
    this.mvrisModelCode = data.MvrisModelCode;
    this.vin = data.Vin;
    this.vrm = data.Vrm;
    this.dateFirstRegistered = data.DateFirstRegistered;
    this.dateScrapped = data.DateScrapped;
    this.doorPlan = data.DoorPlan;
    this.yearMonthFirstRegistered = data.YearMonthFirstRegistered;
    this.vinLast5 = data.VinLast5;
    this.vehicleUsedBeforeFirstRegistration =
      data.VehicleUsedBeforeFirstRegistration;
    this.maxPermissibleMass = data.MaxPermissibleMass;
    this.make = data.Make;
    this.makeModel = data.MakeModel;
    this.transmissionType = data.TransmissionType;
    this.seatingCapacity = data.SeatingCapacity;
    this.fuelType = data.FuelType;
    this.co2Emissions = data.Co2Emissions;
    this.imported = data.Imported;
    this.mvrisMakeCode = data.MvrisMakeCode;
    this.previousVrmNi = data.PreviousVrmNi;
    this.vinConfirmationFlag = data.VinConfirmationFlag;
  }
}
