export class VehicleRegistration {
  dateOfLastUpdate;
  colour;
  vehicleClass;
  certificateOfDestructionIssued;
  engineNumber;
  engineCapacity;
  transmissionCode;
  exported;
  yearOfManufacture;
  wheelPlan;
  dateExported;
  scrapped;
  transmission;
  dateFirstRegisteredUk;
  model;
  gearCount;
  importNonEu;
  previousVrmGb;
  grossWeight;
  doorPlanLiteral;
  mvrisModelCode;
  vin;
  vrm;
  dateFirstRegistered;
  dateScrapped;
  doorPlan;
  yearMonthFirstRegistered;
  vinLast5;
  vehicleUsedBeforeFirstRegistration;
  maxPermissibleMass;
  make;
  makeModel;
  transmissionType;
  seatingCapacity;
  fuelType;
  co2Emissions;
  imported;
  mvrisMakeCode;
  previousVrmNi;
  vinConfirmationFlag;

  constructor(data) {
    this.dateOfLastUpdate = data.DateOfLastUpdate;
    this.colour = data.Colour;
    this.vehicleClass = data.VehicleClass;
    this.certificateOfDestructionIssued = data.CertificateOfDestructionIssued;
    this.engineNumber = data.EngineNumber;
    this.engineCapacity = data.EngineCapacity;
    this.transmissionCode = data.TransmissionCode;
    this.exported = data.Exported;
    this.yearOfManufacture = data.YearOfManufacture;
    this.wheelPlan = data.WheelPlan;
    this.dateExported = data.DateExported;
    this.scrapped = data.Scrapped;
    this.transmission = data.Transmission;
    this.dateFirstRegisteredUk = data.DateFirstRegisteredUk;
    this.model = data.Model;
    this.gearCount = data.GearCount;
    this.importNonEu = data.ImportNonEu;
    this.previousVrmGb = data.PreviousVrmGb;
    this.grossWeight = data.GrossWeight;
    this.doorPlanLiteral = data.DoorPlanLiteral;
    this.mvrisModelCode = data.MvrisModelCode;
    this.vin = data.Vin;
    this.vrm = data.Vrm;
    this.dateFirstRegistered = data.DateFirstRegistered;
    this.dateScrapped = data.DateScrapped;
    this.doorPlan = data.DoorPlan;
    this.yearMonthFirstRegistered = data.YearMonthFirstRegistered;
    this.vinLast5 = data.VinLast5;
    this.vehicleUsedBeforeFirstRegistration =
      data.VehicleUsedBeforeFirstRegistration;
    this.maxPermissibleMass = data.MaxPermissibleMass;
    this.make = data.Make;
    this.makeModel = data.MakeModel;
    this.transmissionType = data.TransmissionType;
    this.seatingCapacity = data.SeatingCapacity;
    this.fuelType = data.FuelType;
    this.co2Emissions = data.Co2Emissions;
    this.imported = data.Imported;
    this.mvrisMakeCode = data.MvrisMakeCode;
    this.previousVrmNi = data.PreviousVrmNi;
    this.vinConfirmationFlag = data.VinConfirmationFlag;
  }
}
